 <form method="post" action="connexion" id="login">
                
                    <label for="email">Email</label>
                    <input type="email" name="email" id="email" />
                    
                    <label for="password">Mot de passe</label>
                    <input type="password" name="password" id="password" />
                    
                    <input type="hidden" name="formName" value="login">
                    
                    <input type="submit" value="Envoyer"/>
            </form>