 <form method="post" action="connexion">
                
                    <label for="email2">Email</label>
                    <input type="email" name="email2" id="email2" />
                    
                    <label for="password2">Mot de passe</label>
                    <input type="password" name="password2" id="password2" />
                    
                    <input type="submit" value="Envoyer"/>
            </form>