 <form method="post" action="connexion" id="login">
                
                    <label for="emailLogin">Email</label>
                    <input type="email" name="email" id="emailLogin" required>
                    
                    <label for="passwordLogin">Mot de passe</label>
                    <input type="password" name="password" id="passwordLogin" required>
                    
                    <input type="hidden" name="formName" value="login">
                    
                    <input class="submit" type="submit" value="Envoyer"/>
            </form>