<section class="register">
 <form method="post" action="index.php?route=register">
                
                    <label for="lastname">Nom</label>
                    <input type="text" name="lastname" id="lastname" />
                    
                    <label for="firstname">Prénom</label>
                    <input type="text" name="firstname" id="firstname" />
                    
                    <label for="email">Email</label>
                    <input type="email" name="email" id="email" />
                    
                    <label for="password">Mot de passe</label>
                    <input type="password" name="password" id="password" />
                    
                    <label for="confirmPassword">Confirmer le mot de passe </label>
                    <input type="password" name="confirmPassword" id="confirmPassword" />
                    
                    <input type="submit" value="Envoyer"/>
            </form>
</section>