<form id="regist" method="post" action="register">
               
                    <label for="firstnameRegister">Prénom</label>
                    <input type="text" name="firstname" id="firstnameRegister" required>
                    
                    <label for="lastnameRegister">Nom</label>
                    <input type="text" name="lastname" id="lastnameRegister" required>
                    
                    <label for="emailRegister">Email</label>
                    <input type="email" name="email" id="emailRegister" required>
                    
                    <label for="passwordRegister">Mot de passe</label>
                    <input type="password" name="password" id="passwordRegister" required>
                    
                    <label for="confirmPasswordRegister">Confirmer le mot de passe </label>
                    <input type="password" name="confirmPassword" id="confirmPasswordRegister" required>
                    
                    <input type="hidden" name="formName" value="register">
                    
                    <input class="submit" type="submit" value="Envoyer"/>
            </form>