<form id="regist" method="post" action="register">
                
                    <label for="firstname">Prénom</label>
                    <input type="text" name="firstname" id="firstname" />
                    
                    <label for="lastname">Nom</label>
                    <input type="text" name="lastname" id="lastname" />
                    
                    <label for="email">Email</label>
                    <input type="email" name="email" id="email" />
                    
                    <label for="password">Mot de passe</label>
                    <input type="password" name="password" id="password" />
                    
                    <label for="confirmPassword">Confirmer le mot de passe </label>
                    <input type="password" name="confirmPassword" id="confirmPassword" />
                    
                    <input type="hidden" name="formName" value="register">
                    
                    <input type="submit" value="Envoyer"/>
            </form>