<h1>Boutique</h1>

    <?php 
    foreach($data["category"] as $category){ 
    ?>
    <ul>
        <li><h2><?= $category->getName() ?></h2></li>
        <li>
            <a href="https://kilyangerard.sites.3wa.io/res03-projet-final/projet/boutique/<?=$category->getSlug()?>">
            <figure><img src="<?= $category->getImgURL()?>"></figure>
            </a>
        </li>
    </ul>
       <?php } ?>