<main id="boutique">
<h1>Boutique</h1>
    <section id="categorie">
        <ul>
        <?php 
        foreach($data["category"] as $category){ 
        ?>
            <li>
                <h2><?= $category->getName() ?></h2>
                <a  href="https://kilyangerard.sites.3wa.io/res03-projet-final/projet/boutique/<?=$category->getSlug()?>">
                <figure><img src="/res03-projet-final/projet/<?= $category->getImgURL()?>" alt="<?= $category->getName()?>"></figure>
                </a>
            </li>
        <?php } ?>
        </ul>
    </section>
</main>