<!doctype html>
<html lang="fr">
<head>
    <meta charset="utf-8">
    <title>MM</title>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href="/res03-projet-final/projet/assets/styles/css/style.css">
</head>
</head>
    <body>
        <header>
            <nav>
                <ul>
                    <?php 
                    if (!isset($_SESSION["Connected"]))
                    { ?>
                        <li><a href="https://kilyangerard.sites.3wa.io/res03-projet-final/projet/connexion">connexion</a></li>
                    <?php } ?>
                    <li><a href="https://kilyangerard.sites.3wa.io/res03-projet-final/projet/boutique">boutique</a></li>
                    <li><a href="">Instagraam</a></li>
                </ul>
            </nav>
        </header>
        <main>
            <?php require "templates/".$template."/".$template.".phtml";?>
        </main>
    </body>
    
</html>