<!doctype html>
<html lang="fr">
<head>
    <meta charset="utf-8">
    <title>MM</title>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href="/res03-projet-final/projet/assets/styles/css/style.css">
</head>
</head>
    <body>
        <header>
            
        </header>
        <main>
            <?php require "templates/".$template."/".$template.".phtml";?>
        </main>
    </body>
    
</html>
