<!doctype html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="title" content="MM Pâtisserie" />
    <meta name="description" content="Boutique de pâtisserie en ligne" />
    <meta name="keywords" content="pâtisserie, confiserie, chocolat, evenementiels" />
    <meta name="author" content="Killyan Gerard" />
    <meta name="referrer" content="origin" />
    <meta property="og:title" content="MM Pâtisserie" />   
    <meta property="og:type" content="Boutique de pâtisserie"/>  
    <meta property="og:url" content="https://kilyangerard.sites.3wa.io/res03-projet-final/projet/accueil" />
    <meta property="og:image" content="https://cdn.discordapp.com/attachments/910185843371671562/1100093402084806717/RcLTWF9E-modified.png" />
    <meta property="og:description" content="Pâtisserie, confiserie, chocolat" />
    <meta property="og:locale" content="fr_FR" />
    <meta property="og:site_name" content="MM"/>
    <title>MM</title>
    <link rel="stylesheet" href="/res03-projet-final/projet/assets/styles/css/style.css">
    <script src="https://kit.fontawesome.com/c326a33220.js" crossorigin="anonymous"></script>
</head>
    <body>
        <header>
            <h1><a href="https://kilyangerard.sites.3wa.io/res03-projet-final/projet/admin">Admin</a></h1>
            <div id="logoAdmin">
          
            </div>
            <h2><a href="https://kilyangerard.sites.3wa.io/res03-projet-final/projet/deconnexion">déconnexion</a></h2>
        </header>
        
        <?php require "templates/".$template."/".$template.".phtml";?>
            
    </body>
</html>
