<!doctype html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="title" content="MM Pâtisserie" />
    <meta name="description" content="Boutique de pâtisserie en ligne" />
    <meta name="keywords" content="pâtisserie, confiserie, chocolat, evenementiels" />
    <meta name="author" content="Killyan Gerard" />
    <meta name="referrer" content="origin" />
    <meta property="og:title" content="MM Pâtisserie" />   
    <meta property="og:type" content="Boutique de pâtisserie"/>  
    <meta property="og:url" content="https://kilyangerard.sites.3wa.io/res03-projet-final/projet/accueil" />
    <meta property="og:image" content="https://cdn.discordapp.com/attachments/910185843371671562/1100093402084806717/RcLTWF9E-modified.png" />
    <meta property="og:description" content="Pâtisserie, confiserie, chocolat" />
    <meta property="og:locale" content="fr_FR" />
    <meta property="og:site_name" content="MM"/>
    <title>MM</title>
    <link rel="stylesheet" href="/res03-projet-final/projet/assets/styles/css/style.css">
    <script src="https://kit.fontawesome.com/c326a33220.js" crossorigin="anonymous"></script>
</head>
    <body>
        <header>
            <nav class="navbar">
                <div class="logoNav">
                    <a href="https://kilyangerard.sites.3wa.io/res03-projet-final/projet/accueil">
                        
                    </a>
                </div>
                <ul>
                    <?php 
                    if (!isset($_SESSION["Connected"]))
                    { ?>
                        <li><a href="https://kilyangerard.sites.3wa.io/res03-projet-final/projet/connexion">connexion</a></li>
                    <?php }
                    else if ((isset($_SESSION["Connected"])) && ($_SESSION["Connected"]!=false))
                    { ?>  
                        <li><a href="https://kilyangerard.sites.3wa.io/res03-projet-final/projet/deconnexion">déconnexion</a></li>
                        <li><a href="https://kilyangerard.sites.3wa.io/res03-projet-final/projet/mon-compte/panier">Panier</a></li>
                        <li><a href="https://kilyangerard.sites.3wa.io/res03-projet-final/projet/mon-compte/favoris">Favoris</a></li>
                        <li><a href="https://kilyangerard.sites.3wa.io/res03-projet-final/projet/mon-compte"><?= $data[0]->getFirstname(); ?></a></li>
                    <?php } ?>
                        <li><a href="https://kilyangerard.sites.3wa.io/res03-projet-final/projet/boutique">boutique</a></li>
                        <li><a href="">Instagraam</a></li>
                </ul>
            </nav>
            <div id="logo">
      
            </div>
        </header>
        
        <?php require "templates/".$template."/".$template.".phtml";?>
        
        <footer class="footer">
            <section>
                <h2 class="hidden">Contact</h2>
    			<ul class="contact">
    				<li><i class="fa fa-map-marker"></i>35 rue. lorem ipsum, lorem ipsum</li>
    				<li><i class="fa fa-phone"></i>02846125415</li>
    				<li><i class="fa fa-envelope"></i><a href="">support@email.com</a></li>
    			</ul>
    			<ul class="reseaux">
    					<li><a href=""><i class="fa fa-facebook"></i></a></li>
    					<li><a href=""><i class="fa fa-twitter"></i></a></li>
    					<li><a href=""><i class="fa fa-linkedin"></i></a></li>
    			</ul>
    		</section>
    		<section class="logo">
    		    <h2 class="hidden">Logo</h2>
    		    <div>
            			     
                </div>
            </section>
            <section>
    			<h2>Contact</h2>
    			<form>
    				<input type="text" name="email" placeholder="Email">
    				<textarea name="message" placeholder="Message"></textarea>
    				<button>Envoyer</button>
    			</form>
    		</section>
    	</footer>
    </body>
</html>
 