<!doctype html>
<html lang="fr">
<head>
    <meta charset="utf-8">
    <title>MM</title>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href="assets/styles/css/style.css">
    <script src="https://kit.fontawesome.com/dbf8b52bf4.js" crossorigin="anonymous"></script>
</head>
</head>
    <body>
        <header>
            <nav>
                <ul>
                    <?php 
                    if (!isset($_SESSION["Connected"]))
                    { ?>
                        <li><a href="https://kilyangerard.sites.3wa.io/res03-projet-final/projet/connexion">connexion</a></li>
                    <?php }
                    else if ((isset($_SESSION["Connected"])) && ($_SESSION["Connected"]!=false))
                    { ?>
                        <li><a href="https://kilyangerard.sites.3wa.io/res03-projet-final/projet/deconnexion">déconnexion</a></li>
                        <li><a href="https://kilyangerard.sites.3wa.io/res03-projet-final/projet/mon-compte/panier">Panier</a></li>
                        <li><a href="https://kilyangerard.sites.3wa.io/res03-projet-final/projet/mon-compte/favoris">Favoris</a></li>
                        <li><a href="https://kilyangerard.sites.3wa.io/res03-projet-final/projet/mon-compte"><?= $data[0]->getFirstname(); ?></a></li>
                    <?php } ?>
                        <li><a href="https://kilyangerard.sites.3wa.io/res03-projet-final/projet/boutique">boutique</a></li>
                        <li><a href="">Instagraam</a></li>
                </ul>
            </nav>
        </header>
        <h1>Privé</h1>
        <main>
            <?php require "templates/".$template."/".$template.".phtml";?>
        </main>
    </body>
</html>
<script type="module" src="/res03-projet-final/projet/assets/js/main.js"></script> 