<!doctype html>
<html lang="fr">
<head>
    <meta charset="utf-8">
    <title>MM</title>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href="/res03-projet-final/projet/assets/styles/css/style.css">
    <script src="https://kit.fontawesome.com/c326a33220.js" crossorigin="anonymous"></script>
</head>
</head>
    <body>
        <header>
            <nav class="navbar">
                
                 <figure>
                    <a href="https://kilyangerard.sites.3wa.io/res03-projet-final/projet/accueil">
                        
                    </a>
                </figure>
                <ul>
                    <?php 
                    if (!isset($_SESSION["Connected"]))
                    { ?>
                        <li><a href="https://kilyangerard.sites.3wa.io/res03-projet-final/projet/connexion">connexion</a></li>
                    <?php }
                    else if ((isset($_SESSION["Connected"])) && ($_SESSION["Connected"]!=false))
                    { ?>  
                        <li><a href="https://kilyangerard.sites.3wa.io/res03-projet-final/projet/deconnexion">déconnexion</a></li>
                        <li><a href="https://kilyangerard.sites.3wa.io/res03-projet-final/projet/mon-compte/panier">Panier</a></li>
                        <li><a href="https://kilyangerard.sites.3wa.io/res03-projet-final/projet/mon-compte/favoris">Favoris</a></li>
                        <li><a href="https://kilyangerard.sites.3wa.io/res03-projet-final/projet/mon-compte"><?= $data[0]->getFirstname(); ?></a></li>
                    <?php } ?>
                        <li><a href="https://kilyangerard.sites.3wa.io/res03-projet-final/projet/boutique">boutique</a></li>
                        <li><a href="">Instagraam</a></li>
                </ul>
            </nav>
        </header>
        
        
            <?php require "templates/".$template."/".$template.".phtml";?>
        
        
        <footer class="footer">
            
            <section>
			<ul class="contact">
				<li><i class="fa fa-map-marker"></i>35 rue. lorem ipsum, lorem ipsum</li>
				<li><i class="fa fa-phone"></i>02846125415</li>
				<li><i class="fa fa-envelope"></i><a href="">support@email.com</a></li>
			</ul>
			<ul class="reseaux">

					<li><a href=""><i class="fa fa-facebook"></i></a></li>
					<li><a href=""><i class="fa fa-twitter"></i></a></li>
					<li><a href=""><i class="fa fa-linkedin"></i></a></li>
					<li><a href=""><i class="fa fa-github"></i></a></li>

			</ul>
			</section>
			<section class="logo">
			    <h2 class="hidden">hidden</h2>
			    <figure>
            			     
                </figure>
            </section>
            <section>

				<h2>Contact</h2>

				<form action="" method="post">

					<input type="text" name="email" placeholder="Email">
					<textarea name="message" placeholder="Message"></textarea>
					<button>Envoyer</button>

				</form>

			</section>
            
		</footer>
    </body>
</html>
 