<main id="commandes">
    <section id="comm">
    <h1>Toutes mes commandes</h1>
    <aside id="asideCompte">
        <ul>
            <li><a href="https://kilyangerard.sites.3wa.io/res03-projet-final/projet/mon-compte">Mon Compte</a></li>
            <li><a href="https://kilyangerard.sites.3wa.io/res03-projet-final/projet/mon-compte/favoris">Mes Favoris</a></li>
            <li><a href="https://kilyangerard.sites.3wa.io/res03-projet-final/projet/mon-compte/panier">Mon Panier</a></li>
        </ul>
    </aside>
         <?php
            foreach($data[2] as $orders){
                 foreach($orders as $order){
        ?>
        <section>
            <h2 class="hidden">Section toute les tables</h2>
            <table>
                <thead>
                    <tr>
                        <th>Image du produit</th>
                        <th>Nom du produit</th>
                        <th>Taille du produit</th>
                        <th>Nombre de produits commander</th>
                        <th>prix du produit</th>
                        <th>total de la commande</th>
                    </tr>
                </thead>
                <tbody>
                <?php foreach($order as $Order){ ?>
                    <tr>
                       
                        <td>
                            <figure>
                                <img alt="<?= $Order['name']; ?>" src="/res03-projet-final/projet/<?= $Order['url']; ?>">
                            </figure>
                        </td>
                        <td><?= $Order['name']; ?></td>
                        <td><?= $Order['size']; ?></td>
                        <td><?= $Order['number']; ?></td>
                        <td><?php $price = $Order['price']*$Order['number']*$Order['size']; echo $price; ?> €</td>
                <?php } ?>
                        <td class="total"><?php echo $order[0]["total_price"]; ?> €</td>
                        
                    </tr>
                     
                </tbody>
            </table>
        </section>
       <?php  } } ?>
       
    </section>
    
</main>