<section class="createallergen">
    <h2>Creation d'allergen</h2>
    <?php  require  '_allergen-form.phtml'; ?>
</section>
<h2><a href="https://kilyangerard.sites.3wa.io/res03-projet-final/projet/admin">revenir aux menu admin</a></h2>
<section>
<h1>Toutes les allergens</h1>
<table>
    <thead>
        <tr>
            <th>Nom</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        <?php 
    foreach($data as $allergen){ 
    ?>
        <tr>
            <td><?= $allergen->getName() ?></td>
            <td>
               <a href="https://kilyangerard.sites.3wa.io/res03-projet-final/projet/admin/allergen/delete/<?=$allergen->getSlug()?>">Supprimer</a>
                <a href="https://kilyangerard.sites.3wa.io/res03-projet-final/projet/admin/allergen/update/<?=$allergen->getSlug()?>">Modifier</a>
            </td>
        </tr>
    <?php } ?>
    </tbody>
</table>
</section>