 <form method="post" action="/res03-projet-final/projet/admin/ingredient/update/<?php echo($data["ingredient"]->getName()); ?>" id="editingredient">
  
                    <label for="id">Id</label>
                    <input type="text" value="<?php echo($data["ingredient"]->getId()); ?>" 
                    name="id" id="id" disabled/>
                
                    <label for="name">Name</label>
                    <input type="text" name="name" id="name" value="<?php echo($data["ingredient"]->getName()); ?>"/>
                    
                    <input type="hidden" name="formName" value="editingredient">
                    <input type="submit" value="Envoyer"/>
            </form>