 <form method="post" action="category/create" id="createcategory">
                
                    <label for="name">Name</label>
                    <input type="name" name="name" id="name" />
                    
                    <label for="url">URL</label>
                    <input type="url" name="url" id="url" />
                    
                    <input type="hidden" name="formName" value="createcategory">
                    
                    <input type="submit" value="Envoyer"/>
 </form>