 <form method="post" action="category/create" id="createcategory" enctype="multipart/form-data">
                
                    <label for="name">Name</label>
                    <input type="name" name="name" id="name" />
                    
                    <label for="url">Importer image</label>
                    <input type="file" name="url" id="url" />
                    
                    <input type="hidden" name="formName" value="createcategory">
                    
                    <input type="submit" value="Envoyer"/>
 </form>