 <form method="post" action="/res03-projet-final/projet/admin/category/update/<?php echo($data["category"]->getSlug()); ?>" id="editcategory" enctype="multipart/form-data">
  
                    <label class="hidden" for="id">Id</label>
                    <input type="text" value="<?php echo($data["category"]->getId()); ?>" 
                    name="id" class="hidden" id="id" disabled/>
                
                    <label for="name">Name</label>
                    <input type="text" name="name" id="name" value="<?php echo($data["category"]->getName()); ?>"/>
                    
                    <label for="url">Importer image</label>
                    <input type="file"  name="url" id="url" />
                    
                    <input type="hidden" name="formName" value="editcategory">
                    <input class="submit" type="submit" value="Envoyer"/>
            </form>