 <form method="post" action="ingredient/create" id="createingredient">
                
                    <label for="name">Name</label>
                    <input type="name" name="name" id="name" />
                    
                    <input type="hidden" name="formName" value="createingredient">
                    
                    <input class="submit" type="submit" value="Envoyer"/>
 </form>