<main class="createAdmin">
    <h2>Creation d'ingredient</h2>
    <?php  require  '_ingredient-form.phtml'; ?>
<h2>Tous les ingrédients</h2>
<table>
    <thead>
        <tr>
            <th>Nom</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        <?php 
    foreach($data as $ingredient){ 
    ?>
        <tr>
            <td><?= $ingredient->getName() ?></td>
            <td>
               <a href="https://kilyangerard.sites.3wa.io/res03-projet-final/projet/admin/ingredient/delete/<?=$ingredient->getSlug()?>">Supprimer</a>
                <a href="https://kilyangerard.sites.3wa.io/res03-projet-final/projet/admin/ingredient/update/<?=$ingredient->getSlug()?>">Modifier</a>
            </td>
        </tr>
    <?php } ?>
    </tbody>
</table>
</main>