 <form method="post"  action="image/create" id="createimage"  enctype="multipart/form-data">
                
                    <label for="image">Importer image</label>
                    <input type="file" name="image" id="image" />
                    
                    <label for="description">Description</label>
                    <input type="text" name="description" id="description" />
                    
                    <label for="product_id">product_id</label>
                    <input type="number" name="product_id" id="product_id" />
                    
                    <input type="hidden" name="formName" value="createimage">
                    
                    <input type="submit" value="Envoyer"/>
 </form>