<section>
<h1><?php 
foreach($data as $user)
{
    echo $user->getFirstname() ;
}
    
    ?></h1>
<table>
    <thead>
        <tr>
            <th>Prénom</th>
            <th>Nom</th>
            <th>Email</th>
        </tr>
    </thead>
    <tbody>
        <?php 
    foreach($data as $user){ 
    ?>
        <tr>
            <td><?= $user->getFirstname() ?></td>
            <td><?= $user->getLastname()?></td>
            <td><?= $user->getEmail()?></td>
        </tr>
    <?php } ?>
    </tbody>
</table>
</section>

<h2><a href="https://kilyangerard.sites.3wa.io/res03-projet-final/projet/admin/user">revenir aux utilisateurs</a></h2>
<section>
<h1>commande</h1>
<?php 
    foreach($data as $user)
    {    ?>
<table>
    <thead>
        <tr>
            <th>Produit</th>
            <th>Taille</th>
            <th>Quantité</th>
            <th>Prix total</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        
        <tr>
            <td><?= $user->get()?></td>
            <td><?= $user->get()?></td>
            <td><?= $user->get()?></td>
            <td><?= $user->get()?></td>
            <td>
               <a href="https://kilyangerard.sites.3wa.io/res03-projet-final/projet/admin/user/delete/<?=$u->get()?>">Supprimer</a>
               <a href="https://kilyangerard.sites.3wa.io/res03-projet-final/projet/admin/user/info/<?=$u->get()?>">Info</a>
            </td>
        </tr>
    </tbody>
</table>
<?php } ?>
</section>