<main id="userAdmin">
    <h2><?= $data[0]->getFirstname() ?></h2>
    <table id ="tableUser">
        <thead>
            <tr>
                <th>Prénom</th>
                <th>Nom</th>
                <th>Email</th>
                <?php if(isset($data[1])){ ?>
                <th>Adresse</th>
                <?php } ?>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td><?= $data[0]->getFirstname() ?></td>
                <td><?= $data[0]->getLastname()?></td>
                <td><?= $data[0]->getEmail()?></td>
                <?php if(isset($data[1])){ ?>
                <td><?php if(isset($data[1])){ echo $data[1]->getNumber();?> <?php echo $data[1]->getStreet(); ?> , <?php echo $data[1]->getCity();?> <?php echo $data[1]->getZipcode();  }  ?></td>
                <?php } ?>
            </tr>
        </tbody>
    </table>
    <?php if(isset($data[2])){ ?>
    <section id="sectionCommandes">
        <h2>Commandes de <?= $data[0]->getFirstname() ?> <?= $data[0]->getLastname()?></h2>
        <?php
                foreach($data[2] as $orders){
                     foreach($orders as $order){
            ?>
            
            <table>
                <thead>
                    <tr>
                        <th>Image du produit</th>
                        <th>Nom du produit</th>
                        <th>Taille du produit</th>
                        <th>Nombre de produits commander</th>
                        <th>prix du produit</th>
                        <th>total de la commande</th>
                    </tr>
                </thead>
                <tbody>
                <?php foreach($order as $Order){ ?>
                    <tr>
                       
                        <td>
                            <img src="/res03-projet-final/projet/<?= $Order['url']; ?>">
                        </td>
                        <td><?= $Order['name']; ?></td>
                        <td><?= $Order['size']; ?></td>
                        <td><?= $Order['number']; ?></td>
                        <td><?php $price = $Order['price']*$Order['number']*$Order['size']; echo $price; ?> €</td>
                <?php } ?>
                        <td id="total"><?php echo $order[0]["total_price"]; ?> €</td>
                        
                    </tr>
                     
                </tbody>
            </table>
       
           <?php  } } ?>
       </section>
       <?php } ?>
       <h2><a href="https://kilyangerard.sites.3wa.io/res03-projet-final/projet/admin/user">revenir aux utilisateurs</a></h2>
</main>