<main id="mon-compte">
    <h1>Mon compte</h1>
    
    <section id="SectionInfoPerso">
       <h2 class="hidden">Info Perso</h2>
        <ul id="ulListeInfo">
            <li>Nom : <p><?= $data[0]->getLastname(); ?></p></li>
            <li>Prénom : <p><?= $data[0]->getFirstname(); ?></p></li>
            <li>Email : <p><?= $data[0]->getEmail(); ?></p></li>
            <li>Adresse : <p><?php if(isset($data[1])){ echo $data[1]->getNumber();?> <?php echo $data[1]->getStreet(); ?> , <?php echo $data[1]->getCity();?> <?php echo $data[1]->getZipcode();  }  ?></p></li>
        
        <li id="editform"><button>modifier</button></li>
        <li id="editaddress"><button>Créer ou modifier son adresse</button></li>
        </ul>
    
        <aside id="asideCompte">
            <ul>
                <li><a href="https://kilyangerard.sites.3wa.io/res03-projet-final/projet/mon-compte/mes-commandes">Mes Commandes</a></li>
                <li><a href="https://kilyangerard.sites.3wa.io/res03-projet-final/projet/mon-compte/favoris">Mes Favoris</a></li>
                <li><a href="https://kilyangerard.sites.3wa.io/res03-projet-final/projet/mon-compte/panier">Mon Panier</a></li>
            </ul>
        </aside>
    
    <form class="hidden"  method="post" action="/res03-projet-final/projet/mon-compte/edituser" id="edituser">
              
        <input value="<?= $data[0]->getId(); ?>" type="number" class="hidden" name="id">
        <fieldset>
            <label for="firstname">Prénom</label>
            <input value="<?= $data[0]->getFirstname(); ?>" type="text" name="firstname" id="firstname" required>
        </fieldset>
        <fieldset>
        <label for="lastname">Nom</label>
        <input value="<?= $data[0]->getLastname(); ?>" type="text" name="lastname" id="lastname" required>
        </fieldset>
        <fieldset>
        <label for="email">Email</label>
        <input value="<?= $data[0]->getEmail(); ?>" type="email" name="email" id="email" required>
        </fieldset>
        <fieldset>
        <label for="password">Mot de passe</label>
        <input type="password" name="password" id="password" required>
        </fieldset>
        <fieldset>
        <label for="confirmPassword">Confirmer le mot de passe </label>
        <input type="password" name="confirmPassword" id="confirmPassword" required>
        </fieldset>
        <input value="<?= $data[0]->getAddress_Id(); ?>" type="number" class="hidden" name="addressid">
        
        <input type="hidden" name="formName" value="edituser">
        <input class="sub" type="submit" value="Envoyer"/>
    </form>
    
    <form class="hidden" method="post" action="/res03-projet-final/projet/mon-compte/addAddress" id="createAddress">
            
        <input value="<?= $data[0]->getId(); ?>" type="number" class="hidden" name="id" id="id">
        <input value="<?php if(isset($data[1])) { echo $data[1]->getId(); } ?>" type="number" class="hidden" name="addressid" id="addressid">
        
        <fieldset>
        <label for="street">Rue ou Avenue</label>
        <input value="<?php if(isset($data[1])) { echo $data[1]->getStreet(); } ?>" type="text" name="street" id="street" required>
        </fieldset>
        <fieldset>
        <label for="number">Numéro</label>
        <input value="<?php if(isset($data[1])) { echo $data[1]->getNumber(); } ?>" type="text" name="number" id="number" required>
        </fieldset>
        <fieldset>
        <label for="city">Ville</label>
        <input value="<?php if(isset($data[1])) { echo $data[1]->getCity(); } ?>" type="text" name="city" id="city" required>
        </fieldset>
        <fieldset>
        <label for="zipcod">Code postal</label>
        <input value="<?php if(isset($data[1])) { echo $data[1]->getZipcode(); } ?>" type="text" name="zipcod" id="zipcod" required>
        </fieldset>
        <input type="hidden" name="formName" value="createAddress">
        <input class="sub" type="submit" value="Envoyer">
    </form>
</section>
    <script type="module" src="/res03-projet-final/projet/assets/js/account.js"></script>
</main>