 <form method="post" action="product/create" id="createproduct" enctype="multipart/form-data">
                
                    <label for="name">Name</label>
                    <input type="text" name="name" id="name" />
                    
                    <label for="description">description</label>
                    <input type="text" name="description" id="description" />
                    
                    <label for="price">price</label>
                    <input type="number" step="0.01" name="price" id="price" />
                    
                    <label for="category_id">dans quel catégorie ?</label>
                    <select name="category_id" id="category_id">
                        <option value=""></option>
                         <?php 
                              foreach($data["categorys"] as $category){ ?>
                              
                        <option value="<?= $category->getId()?>"><?= $category->getName()?></option>
                         <?php } ?>
                    </select>
                     
                    <label for="ingredient">avec quel ingredient ?</label>
                    <select name="ingredient" id="ingredient">
                        <option value=""></option>
                         <?php var_dump($data["ingredients"]);
                              foreach($data["ingredients"] as $ingredient){ ?>
                              
                        <option value="<?= $ingredient->getId()?>"><?= $ingredient->getName()?></option>
                         <?php } ?>
                    </select>
                    
                    <label for="allergen">avec quel allergen ?</label>
                    <select name="allergen" id="allergen">
                        <option value=""></option>
                         <?php 
                              foreach($data["allergens"] as $allergen){ ?>
                              
                        <option value="<?= $allergen->getId()?>"><?= $allergen->getName()?></option>
                         <?php } ?>
                    </select>
                    
                    
                    <label for="image">Importer image</label>
                    <input type="file" name="image" id="image" />
                    
                    <label for="descriptionimg">Description</label>
                    <input type="text" name="descriptionimg" id="descriptionimg" />
                    
                    <input type="hidden" name="formName" value="createproduct">
                    <input type="submit" value="Envoyer"/>
                
 </form>