 <form method="post" action="product/create" id="createproduct" enctype="multipart/form-data">
                
                    <label for="name">Name</label>
                    <input type="text" name="name" id="name" required>
                    
                    <label for="description">description</label>
                    <input class = "textarea" type="text" name="description" id="description" required>
                    
                    <label for="price">price</label>
                    <input type="text" name="price" id="price" required>
                    
                    <label for="category_id">dans quel catégorie ?</label>
                    <select name="category_id" id="category_id">
                        <option value=""></option>
                         <?php 
                              foreach($data["categorys"] as $category){ ?>
                              
                        <option value="<?= $category->getId()?>"><?= $category->getName()?></option>
                         <?php } ?>
                    </select>
                     
                    <section id="section-ingredient">
                        <label for="ingredient">avec quel ingredient ?</label>
                        <select name="ingredient" class="ingredient">
                            <option class="op-ingredient" value=""></option>
                             <?php var_dump($data["ingredients"]);
                                  foreach($data["ingredients"] as $ingredient){ ?>
                                  
                            <option class="data-ingredient" value="<?= $ingredient->getId()?>"><?= $ingredient->getName()?></option>
                             <?php } ?>
                        </select>
                    </section>
                    
                    <section id="section-allergen">
                        <label for="allergen">avec quel allergen ?</label>
                        <select name="allergen" class="allergen">
                            <option class="op-allergen" value=""></option>
                             <?php 
                                  foreach($data["allergens"] as $allergen){ ?>
                                  
                            <option class="data-allergen" value="<?= $allergen->getId()?>"><?= $allergen->getName()?></option>
                             <?php } ?>
                        </select>
                        
                    </section>
                    <input type="hidden" id="allergenData" name="allergenData">
                    <input type="hidden" id="ingredientsData" name="ingredientsData">
                    
                    <label for="image">Importer image</label>
                    <input type="file" name="image" id="image" />
                    
                    <label for="descriptionimg">Description</label>
                    <input  class = "textarea" type="text" name="descriptionimg" id="descriptionimg" />
                    
                    <input type="hidden" name="formName" value="createproduct">
                    <input class="submit" type="submit" value="Envoyer"/>
                
 </form>
