<section class="createproduct">
    <h2>Creation de produits</h2>
    <?php  require  '_product-form.phtml'; ?>
</section>
<h2><a href="https://kilyangerard.sites.3wa.io/res03-projet-final/projet/admin">revenir aux menu admin</a></h2>
<section>
<h1>Toutes les produits</h1>
<table>
    <thead>
        <tr>
            <th>Image du produit</th>
            <th>Nom du produit</th>
        </tr>
    </thead>
    <tbody>
        <?php 
    foreach($data["product"] as $product){ 
        
    ?>
        <tr>
            <td>
                
                   <img <?php // foreach($data["image"] as $image){ ?> height=60px src="/res03-projet-final/projet/<?=// $image->getURL(); ?>"   <?php  } ?>>
            
            </td>
            <td><?= $product->getName() ?></td>
        </tr>
    <?php  } ?>
    </tbody>
</table>
</section>