<main id="productsAdmin">
    <h2>Creation de produits</h2>
    <?php  require  '_product-form.phtml'; ?>
    <h2>Tous les produits</h2>
    <table>
        <thead>
            <tr>
                <th>Image du produit</th>
                <th>Nom du produit</th>
                <th>Description du produit</th>
                <th class="action">Action</th>
            </tr>
        </thead>
        <tbody>
            <?php 
        foreach($data["products"] as $product){ 
            
        ?>
            <tr>
                <td>
                    <img height=60px src="/res03-projet-final/projet/<?php foreach($data["image"] as $image){  if( ($image->getProduct_id()) === ($product->getId()) ){ echo $image->getUrl(); } } ?>">
                </td>
                <td><?= $product->getName() ?></td>
                <td><?= $product->getDescription() ?></td>
                <td class="action">
                   <a href="https://kilyangerard.sites.3wa.io/res03-projet-final/projet/admin/product/delete/<?=$product->getId()?>">Supprimer</a>
                    <a href="https://kilyangerard.sites.3wa.io/res03-projet-final/projet/admin/product/update/<?=$product->getSlug()?>">Modifier</a>
                    <a href="https://kilyangerard.sites.3wa.io/res03-projet-final/projet/admin/product/info/<?=$product->getId()?>">Info</a>
                </td>
            </tr>
        <?php  } ?>
        </tbody>
    </table>
<script type="module" src="/res03-projet-final/projet/assets/js/product.js"></script>
</main>