<section class="createproduct">
    <h2>Creation de produits</h2>
    <?php  require  '_product-form.phtml'; ?>
</section>
<h2><a href="https://kilyangerard.sites.3wa.io/res03-projet-final/projet/admin">revenir aux menu admin</a></h2>
<section>
<h1>Toutes les produits</h1>
<table>
    <thead>
        <tr>
            <th>Nom du produit</th>
            <th>Description du produit</th>
            <th>Action</th>
            <th>ingredients</th>
            <th>allergenes</th>
        </tr>
    </thead>
    <tbody>
        <?php 
    foreach($data["products"] as $product){ 
    ?>
        <tr>
            <td><?= $product->getName() ?></td>
            <td><?= $product->getDescription() ?></td>
            <td>
               <a href="https://kilyangerard.sites.3wa.io/res03-projet-final/projet/admin/product/delete/<?=$product->getSlug()?>">Supprimer</a>
                <a href="https://kilyangerard.sites.3wa.io/res03-projet-final/projet/admin/product/update/<?=$product->getSlug()?>">Modifier</a>
                <a href="https://kilyangerard.sites.3wa.io/res03-projet-final/projet/admin/product/info/<?=$product->getId()?>">Info</a>
            </td>
            <td>
                 <?php 
                foreach($data["ingredients"] as $ingredient){ 
                    echo $ingredient->getName() ;
                } ?>
            </td>
            <td>
                 <?php 
                foreach($data["allergens"] as $allergen){ 
                    echo $allergen->getName() ;
                } ?>
            </td>
        </tr>
    <?php } ?>
    </tbody>
</table>
</section>