
<main id="HomepageAdmin">
    <ul>
        <h2>Accueil</h2>
        <li><a href="https://kilyangerard.sites.3wa.io/res03-projet-final/projet/admin/user">utilisateur</a></li>
        <li><a href="https://kilyangerard.sites.3wa.io/res03-projet-final/projet/admin/category">catégories</a></li>
        <li><a href="https://kilyangerard.sites.3wa.io/res03-projet-final/projet/admin/product">produit</a></li>
        <li><a href="https://kilyangerard.sites.3wa.io/res03-projet-final/projet/admin/ingredient">Ingredients</a></li>
        <li><a href="https://kilyangerard.sites.3wa.io/res03-projet-final/projet/admin/allergen">Allergens</a></li>
    </ul>
</main>