<form method="post" action="/res03-projet-final/projet/admin/product/update/<?php echo($data["product"]->getSlug()); ?>" id="editproduct">
  
        
        <label for="name">Name</label>
        <input type="text" value="<?php echo($data["product"]->getName()); ?>" name="name" id="name" />
        
        <label for="description">description</label>
        <input type="text" value="<?php echo($data["product"]->getDescription()); ?>" name="description" id="description" />
        
        <label for="price">price</label>
        <input type="text" value="<?php echo($data["product"]->getPrice()); ?>" name="price" id="price" />
        
        <label class="hidden" for="category">Catégorie</label>
        <input type="text" value="<?php echo($data["product"]->getCategoryId()); ?>" 
        name="id" class="hidden" id="id" disabled/>
        
        <label class="hidden" for="slug">Slug</label>
        <input type="text" value="<?php echo($data["product"]->getSlug()); ?>" 
        name="id" class="hidden" id="id" disabled/>
        
        <label class="hidden" for="id">Id</label>
        <input type="text" value="<?php echo($data["product"]->getId()); ?>" 
        name="id" class="hidden" id="id" disabled/>
        
        <section id="section-ingredient">
                        <label for="ingredient">avec quel ingredient ?</label>
                        <select name="ingredient" class="ingredient">
                            <option class="op-ingredient" value=""></option>
                             <?php var_dump($data["ingredients"]);
                                  foreach($data["ingredients"] as $ingredient){ ?>
                                  
                            <option class="data-ingredient" value="<?= $ingredient->getId()?>"><?= $ingredient->getName()?></option>
                             <?php } ?>
                        </select>
                    </section>
                    
                    <section id="section-allergen">
                        <label for="allergen">avec quel allergen ?</label>
                        <select name="allergen" class="allergen">
                            <option class="op-allergen" value=""></option>
                             <?php 
                                  foreach($data["allergens"] as $allergen){ ?>
                                  
                            <option class="data-allergen" value="<?= $allergen->getId()?>"><?= $allergen->getName()?></option>
                             <?php } ?>
                        </select>
                        
                    </section>
                    <input type="hidden" id="allergenData" name="allergenData">
                    <input type="hidden" id="ingredientsData" name="ingredientsData">
                    
        <input type="hidden" name="formName" value="editproduct">
        <input class="submit" type="submit" value="Envoyer"/>
</form>