 <form method="post" action="mon-compte/panier" id="createCommande">
                
                    <label for="size">Taille du gateau</label>
                    <input type="number" name="size" id="size" />
                    
                    <label for="number">Nombre de parts</label>
                    <input type="number" name="number" id="number" />
                    
                    <label for="totalPiece">Nombre Total de parts</label>
                    <input type="number" name="totalPiece" id="totalPiece" />
                    
                    <input type="hidden" name="formName" value="createCommande">
                    <input type="submit" value="Envoyer"/>
 </form>