 <header>
            <h2>Mon panier</h2>
            <p id="cart-total-price">Total : </p>
</header>
        <section id="section">
            <ul id="ul">
                
            </ul>
        </section>
        
        <footer>
            <button id="order">Finaliser la commande</button>
        </footer>
        <section id="sec">
            
        </section>
 <h2><a href="/res03-projet-final/projet/boutique">
        revenir a la boutique
</a></h2>


<script type="module" src="/res03-projet-final/projet/assets/js/mainOrder.js"></script> 

<p class="hidden" email="<?= $_SESSION["Connected"][0]["email"];?>" id="userId" idus="<?= $_SESSION["Connected"][0]["id"];?>">hidden</p>
