 <main id="panier">
     <figure id="logo">
      
    </figure>
    <section id="panierSection">
                <h2>Mon panier</h2>
                <section id="section">
                    <ul id="ul">
                        
                    </ul>
                </section>
                <section id="sec">
                    
                </section>
                <footer>
                    <p id="cart-total-price">Total : </p>
                    <p><button class="button" id="order">Finaliser la commande</button></p>
                </footer>
     <aside id="asideCompte">
        <ul>
            <li><a href="https://kilyangerard.sites.3wa.io/res03-projet-final/projet/mon-compte/mes-commandes">Mes Commandes</a></li>
            <li><a href="https://kilyangerard.sites.3wa.io/res03-projet-final/projet/mon-compte/favoris">Mes Favoris</a></li>
            <li><a href="https://kilyangerard.sites.3wa.io/res03-projet-final/projet/mon-compte/panier">Mon Panier</a></li>
        </ul>
    </aside>
    </section>
    <p class="hidden" email="<?= $_SESSION["Connected"][0]["email"];?>" id="userId" idus="<?= $_SESSION["Connected"][0]["id"];?>"></p>
    <script type="module" src="/res03-projet-final/projet/assets/js/mainOrder.js"></script>
</main>