<main id="favorite">
    <h1>Mes favoris</h1>
        <section id="section">
            <h2 class="hidden">Favoris</h2>
            <ul id="ul">
                
            </ul>
            <aside id="asideCompte">
                <ul>
                    <li><a href="https://kilyangerard.sites.3wa.io/res03-projet-final/projet/mon-compte/mes-commandes">Mes Commandes</a></li>
                    <li><a href="https://kilyangerard.sites.3wa.io/res03-projet-final/projet/mon-compte">Mon Compte</a></li>
                    <li><a href="https://kilyangerard.sites.3wa.io/res03-projet-final/projet/mon-compte/panier">Mon Panier</a></li>
                </ul>
            </aside>
        </section>
    <script type="module" src="/res03-projet-final/projet/assets/js/displayFavorite.js"></script>  
</main>