 <header>
            <h2>Mes favoris</h2>
</header>
        <section id="section">
            <ul id="ul">
                
            </ul>
        </section>
        <section id="sec">
            
        </section>
 <h2><a href="/res03-projet-final/projet/boutique">
        revenir a la boutique
</a></h2>
<script type="module" src="/res03-projet-final/projet/assets/js/mainFavorite.js"></script>  