<main id="OneProduct">
    <article id="article">
        <header id="headerArticle">
            <h1><?=$data["product"]->getName()?></h1>
        </header>
        <figure id="media">
            <img src="/res03-projet-final/projet/<?php foreach($data["image"] as $image){ echo $image->getURL(); } ?>" alt="<?php foreach($data["image"] as $image){ echo $image->getDescription(); } ?>">
        </figure>
        <ul id="ulArticle">
            <li id="description"><h2>Description :</h2><p>
                <?php  
                    echo $data["product"]->getDescription(); 
                ?>
            </p></li>
            <li id="ingredients"><h2>Composition :</h2><p>
                <?php
                $ingredient = [];
                foreach($data["ingredients"] as $ingredients)
                {   
                    
                    $ingredient[]= $ingredients->getName(); 
                    
                }
                echo(implode(", ", $ingredient));
                ?>
            </p></li>
            <li id="allergens"><h2>Allergens :</h2><p>
                <?php
                $allergen = [];
                foreach($data["allergens"] as $allergens)
                {   
                    
                    $allergen[]= $allergens->getName(); 
                    
                }
                echo(implode(", ", $allergen));
                ?>
            </p></li>
            <li id="prix" data-price="<?= $data["product"]->getPrice(); ?>">
                <section id="footerArticle">
                    <h2 class="hidden">Footer de mon article</h2>
                    <form>
                        <fieldset>
                            <label for="select">Choisissez une taille</label>
                            <select name="size" id="select">
                                <option value="1">Individuelle</option>
                                <option value="4">4 personnes</option>
                                <option value="6">6 personnes</option>
                                <option value="8">8 personnes</option>
                                <option value="10">10 personnes</option>
                                <option value="12">12 personnes</option>
                            </select>
                        </fieldset>
                    </form>
                    <p> 
                        <?php  
                        echo $data["product"]->getPrice(); 
                        ?>€ / personne
                    </p>
                    <span>
                        <button class="button" id="add-to-cart" data-number="1" data-id="<?php echo $data["product"]->getId(); ?>">Ajouter au panier</button>
                        <button class="add-to-favorite button" data-id="<?php echo $data["product"]->getId(); ?>">Ajouter au favoris</button>
                    </span>
                </section>
            </li>
        </ul>
    </article>
    <aside class="hidden" id="asidePanier">
                <h2>Mon panier</h2>
                <section id="section">
                    <h2 class="hide">Panier</h2>
                    <ul id="ul">
                        
                    </ul>
                </section>
                <footer>
                    <p id="cart-total-price">Total : </p>
                    <p><a class="btn btn-cart-order" href="https://kilyangerard.sites.3wa.io/res03-projet-final/projet/mon-compte/panier">Finaliser la commande</a></p>
                    <p><a class="btn btn-cart-back" href="https://kilyangerard.sites.3wa.io/res03-projet-final/projet/boutique">Continuer mes achats</a></p>
                </footer>    
    </aside>
    <footer id="footer">
        <ul>
        <?php 
        foreach($data["categorys"] as $category){ 
        ?>
        <li>
            <h2><?= $category->getName() ?></h2>
            <a  href="https://kilyangerard.sites.3wa.io/res03-projet-final/projet/boutique/<?=$category->getSlug()?>">
                <figure>
                    <img src="/res03-projet-final/projet/<?= $category->getImgURL()?>" alt="<?= $category->getName()?>">
                </figure>
            </a>
        </li>
        <?php } ?>
        </ul>
    </footer>
    <script type="module" src="/res03-projet-final/projet/assets/js/mainCart.js"></script>
    <script type="module" src="/res03-projet-final/projet/assets/js/addFavorite.js"></script>
</main>