<h2><a href="/res03-projet-final/projet/accueil">
        revenir a l'accueil
    </a></h2>
    <header>
        <h1><?=$data["product"]->getName()?></h1>
    </header>
    <section>
        <ul>
            <li>
                <figure>
                    <img height=60px src="/res03-projet-final/projet/<?php foreach($data["image"] as $image){ echo $image->getURL(); } ?>">
                </figure>
            </li>
            <li>
                <?php foreach($data["ingredients"] as $ingredients)
                {    
                    echo $ingredients->getName(); 
                } ?>
            </li>
            <li>
                <?php foreach($data["allergens"] as $allergens)
                {    
                    echo $allergens->getName(); 
                } ?>
            </li>
            <li>
                <?php  
                    echo $data["product"]->getDescription(); 
                ?>
            </li>
            <li id="prix" price="<?php  
                    echo $data["product"]->getPrice(); 
                ?>">
                <?php  
                    echo $data["product"]->getPrice(); 
                ?>€
            </li>
        </ul>
        <fieldset>
            <form action="" method="post">
                <label for="select">Pour combien de personne ?</label>

                <select name="size" id="select">
                    <option value="1">1</option>
                    <option value="2">2</option>
                    <option value="4">4</option>
                    <option value="6">6</option>
                    <option value="8">8</option>
                    <option value="10">10</option>
                    <option value="12">12</option>
                </select>
            </form>

        </fieldset>
        <button id="add-to-cart" data-number="1" data-id="<?php echo $data["product"]->getId(); ?>">Ajouter au panier</button>
        <button id="add-to-favorite" data-id="<?php echo $data["product"]->getId(); ?>">Ajouter au favoris</button>
        <button>Ajouter au favoris</button>
    </section>
    <aside>
                <header>
                    <h2>Mon panier</h2>
                    <p id="cart-total-price">Total : </p>
                </header>
                <section id="section">
                    <ul id="ul">
                        
                    </ul>
                </section>
                <footer>
                    <a class="btn btn-cart-back" href="https://kilyangerard.sites.3wa.io/res03-projet-final/projet/boutique">Continuer mes achats</a>
                    <a class="btn btn-cart-order" href="https://kilyangerard.sites.3wa.io/res03-projet-final/projet/mon-compte/panier">Finaliser la commande</a>
                </footer>
                
    </aside>
    
    
    <h2><a href="/res03-projet-final/projet/boutique/<?php echo $data["category"]->getSlug(); ?>">
        revenir a la category <?php echo $data["category"]->getName();  ?>
    </a></h2>
    <h2><a href="/res03-projet-final/projet/boutique">
        revenir a la boutique
    </a></h2>
    <script type="module" src="/res03-projet-final/projet/assets/js/mainCart.js"></script>  